apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-configmap
data:
  script.js: |
    "use strict";

    const apiURL = `https://api.openweathermap.org/data/2.5/weather?units=metric`;
    const appKey = `&appid=1dc02c2cda3d32eda98eede7405d0e42`;

    const searchField = document.querySelector(".searchArea input");
    const searchBtn = document.querySelector(".searchArea button");
    const weatherIcon = document.querySelector(".Weather-Icon");

    function city() {
      const inputName = document.querySelector("#impTXT");
      const city = `&q=${inputName.value}`;
      checkWeather(city);
    }

    async function checkWeather(city) {
      const response = await fetch(apiURL + appKey + city);
      var data = await response.json();
      console.log(data);

      document.querySelector(".city").innerHTML = data.name;
      document.querySelector(".temperature").innerHTML = Math.round(data.main.temp) + "°C";
      document.querySelector(".humidity").innerHTML = data.main.humidity + "%";
      document.querySelector(".wind").innerHTML = data.wind.speed + "km/h";

      // Add logic to set weatherIcon.src based on weather conditions
    }

    searchBtn.addEventListener("click", city);

    searchField.addEventListener("keypress", function (event) {
      if (event.key === "Enter") {
        event.preventDefault();
        city();
      }
    });
